app/__init__.py
import os
from flask import *
from .logger_base import log

def create_app():
    app = Flask(__name__)
    app.config.from_mapping( 
        SECRET_KEY        = 'RIEJ030619HNECSNA9',
        DATABASE          = os.environ.get("FLASK_DATABASE"),
        DATABASE_HOST     = os.environ.get("FLASK_DATABASE_HOST"),
        DATABASE_USER     = os.environ.get("FLASK_DATABASE_USER"),
        DATABASE_PASSWORD = os.environ.get("FLASK_DATABASE_PASSWORD")
    )
    #
    from . import views
    app.register_blueprint(views.bp)
    #
    return app

app/views.py
from flask import *
from .descriptions import *

bp = Blueprint('views',__name__,url_prefix='/')

@bp.route('/')
def index():
    return render_template('routes/index.html')
@bp.route('/presentation')
def presentation():
    return render_template('routes/presentation.html')
@bp.route('/vocational_test')
def vocational_test():
    return render_template('routes/test.html')
@bp.route('/careers')
def careers():
    return render_template('routes/careers.html',
                            informatica_concept    = informatica_concept,
                            administracion_concept = administracion_concept,
                            contabilidad_concept   = contabilidad_concept,
                            marketing_concept      = marketing_concept,
                        )
@bp.route('/contact_us')
def contact_us():
    return render_template('routes/contact.html')

###################################################
#                     CAREERS                     #
###################################################

@bp.route('/career/informatica')
def informatica():
    return render_template('routes/career_informatica.html')

@bp.route('/career/administracion')
def administracion():
    return render_template('routes/career_administracion.html')

@bp.route('/career/contabilidad')
def contabilidad():
    return render_template('routes/career_contabilidad.html')

@bp.route('/career/marketing')
def marketing():
    return render_template('routes/career_marketing.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="cecyt12, elegir carrera, carrera, informatica, administracion, contabilidad, marketing digital, test vocacional">
    <meta name="authors" content="Martha Judith Giron Hernández, Raffealla Melina Macías Montoy, Juan Diego Rico Espluga">
    <!-- <meta name="description" content=""> -->
    <meta name="description" content="Es una aplicación web para tutoría y orientación de jóvenes estudiantes del Centro de Estudios Científicos y Tecnológicos n° 12 para facilitar la elección y dar a conocer todas las carreras técnicas que se ofrecen en el plantel del Instituto Politécnico Nacional.">
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#800040">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#800040">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#800040">
    <title>EduCiervos 12 | {% block title %}{% endblock %}</title>
    <!-- ICONS -->
    <meta name="apple-mobile-web-app-title" content="EduCiervos12">
    <meta name="application-name" content="EduCiervos12">
    <meta name="msapplication-TileColor" content="#800040">
    <meta name="theme-color" content="#800040">
    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@200;400&family=Libre+Barcode+128+Text&family=Lobster&family=Metal+Mania&family=Open+Sans&family=PT+Sans:wght@400;700&family=Press+Start+2P&family=Roboto:wght@100;900&family=Shadows+Into+Light&family=Solway&display=swap" rel="stylesheet">
    <!-- FONTAWESOME -->
    <script src="https://kit.fontawesome.com/897a6024ea.js" crossorigin="anonymous"></script>
    <!-- STYLES -->
    <link rel="shortcut icon" href="{{ url_for('static',filename='img/ico/Ciervos.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
</head>
<body>
    <div class="navbar">{% include 'navbar.html' %}</div>
    <div class="content">{% block content %}{% endblock %}</div>
    <div class="footer">{% include 'footer.html' %}</div>
    <!-- Scripts -->
    <script src="/static/js/modernizr.js"></script>
    <script src="/static/js/index.js"></script>
    <script src="https://kit.fontawesome.com/eb496ab1a0.js" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

app/templates/footer.html
<footer class="foo">
    <div class="foo__ipn">
            <picture>
                    <source srcset="/static/img/logo_ipn-white.avif" type="image/avif">
                    <source srcset="/static/img/logo_ipn-white.webp" type="image/webp">
                    <img loading="lazy" src="/static/img/min/logo_ipn-white.png" type="image/png" alt="Logo IPN">
            </picture>
    </div>
    <div class="foo__complaints">
            <h3>Quejas y Sugerencias</h3>
            <picture>
                    <source srcset="/static/img/white-icon_mail.avif" type="image/avif">
                    <source srcset="/static/img/white-icon_mail.webp" type="image/webp">
                    <img loading="lazy" src="/static/img/min/white-icon_mail.png" type="image/png" alt="Complaints IMG">
            </picture>
            <a href="mailto:IPN-CORREO">
                    <i class="fas fa-clipboard-check"></i>
                    <span>correo@correo.com</span>
            </a>
            <a href="tel:5566667777">
                    <i class="fas fa-mobile"></i>
                    <span>(+52) 55 6666 7777</span>
            </a>
    </div>
    <div class="foo__socials">
            <a href="https://www.facebook.com/profile.php?id=100079446507598" target="_blank" class="foo__socials-item" id="foo__socials-fb">
                    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="50" height="50" viewBox="0 0 225 225" style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,225.98438v-225.98437h225.98438v225.98438z" fill="none"></path><g><path d="M112.5,23.4375c-49.18786,0 -89.0625,39.87464 -89.0625,89.0625c0,49.18786 39.87464,89.0625 89.0625,89.0625c49.18786,0 89.0625,-39.87464 89.0625,-89.0625c0,-49.18786 -39.87464,-89.0625 -89.0625,-89.0625z" fill="#146699"></path><path d="M124.55625,136.10625h23.04844l3.61875,-23.41406h-26.67188v-12.79687c0,-9.72656 3.17813,-18.35156 12.27656,-18.35156h14.62031v-20.43281c-2.56875,-0.34688 -8.00156,-1.10625 -18.26719,-1.10625c-21.43594,0 -34.00312,11.32031 -34.00312,37.11094v15.57656h-22.03594v23.41406h22.03594v64.35469c4.36406,0.65625 8.78437,1.10156 13.32187,1.10156c4.10156,0 8.10469,-0.375 12.05625,-0.90938z" fill="#ffffff"></path></g></g></svg>
            </a>
            <a href="https://twitter.com/BurritoPsycho" target="_blank" class="foo__socials-item" id="foo__socials-tt">
                    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="50" height="50" viewBox="0 0 225 225" style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,225.98438v-225.98437h225.98438v225.98438z" fill="none"></path><g><path d="M112.5,18.75c-51.7767,0 -93.75,41.9733 -93.75,93.75c0,51.7767 41.9733,93.75 93.75,93.75c51.7767,0 93.75,-41.9733 93.75,-93.75c0,-51.7767 -41.9733,-93.75 -93.75,-93.75z" fill="#5bcaff"></path><path d="M168.75,80.25c-4.13437,1.83281 -9.37031,3.55312 -14.0625,4.125c4.77187,-2.83125 12.34219,-8.72813 14.0625,-14.0625c-4.45781,2.62031 -12.52031,5.41875 -17.77969,6.43125c-4.2,-4.45312 -10.19063,-6.43125 -16.82812,-6.43125c-12.75,0 -21.64219,10.80469 -21.64219,23.4375v9.375c-18.75,0 -37.03125,-14.28281 -48.40781,-28.125c-2.00156,3.37969 -3.12656,7.33594 -3.12656,11.51719c0,8.52656 7.83281,17.17969 14.03437,21.29531c-3.78281,-0.11719 -10.94531,-3.00469 -14.0625,-4.6875c0,0.075 0,0.16875 0,0.26719c0,11.09531 7.78594,18.62812 18.3375,20.72813c-1.92656,0.52969 -4.275,2.44219 -13.3125,2.44219c2.93438,9.07031 17.68594,13.86562 27.7875,14.0625c-7.90313,6.12656 -21.99375,9.375 -32.8125,9.375c-1.87031,0 -2.88281,0.10313 -4.6875,-0.10781c10.20938,6.46875 24.46875,9.48281 37.5,9.48281c42.45469,0 65.625,-32.42812 65.625,-62.67187c0,-0.99375 -0.03281,-4.32188 -0.08437,-5.29687c4.5375,-3.19688 6.375,-6.54375 9.45937,-11.15625" fill="#ffffff"></path></g></g></svg>
            </a>
            <a href="https://www.instagram.com/Psychoburrito" target="_blank" class="foo__socials-item" id="foo__socials-ig">
                    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="50" height="50" viewBox="0 0 225 225" style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,225.98438v-225.98437h225.98438v225.98438z" fill="none"></path><g fill="#ff0787"><path d="M112.5,15c-53.76,0 -97.5,43.74 -97.5,97.5c0,53.76 43.74,97.5 97.5,97.5c53.76,0 97.5,-43.74 97.5,-97.5c0,-53.76 -43.74,-97.5 -97.5,-97.5zM87.49512,45h49.99511c23.4375,0 42.50977,19.06512 42.50977,42.49512v49.99511c0,23.4375 -19.06512,42.50977 -42.49512,42.50977h-49.99511c-23.4375,0 -42.50977,-19.06512 -42.50977,-42.49512v-49.99511c0,-23.4375 19.06512,-42.50977 42.49512,-42.50977zM87.49512,60c-15.1575,0 -27.49512,12.34477 -27.49512,27.50977v49.99511c0,15.1575 12.34477,27.49512 27.50977,27.49512h49.99511c15.1575,0 27.49512,-12.34477 27.49512,-27.50977v-49.99511c0,-15.1575 -12.34477,-27.49512 -27.50977,-27.49512zM147.50977,72.49512c2.76,0 4.99511,2.23512 4.99511,4.99512c0,2.76 -2.23511,5.00977 -4.99511,5.00977c-2.76,0 -5.00977,-2.24977 -5.00977,-5.00977c0,-2.76 2.24977,-4.99512 5.00977,-4.99512zM112.5,75c20.6775,0 37.5,16.8225 37.5,37.5c0,20.6775 -16.8225,37.5 -37.5,37.5c-20.6775,0 -37.5,-16.8225 -37.5,-37.5c0,-20.6775 16.8225,-37.5 37.5,-37.5zM112.5,90c-12.42641,0 -22.5,10.07359 -22.5,22.5c0,12.42641 10.07359,22.5 22.5,22.5c12.42641,0 22.5,-10.07359 22.5,-22.5c0,-12.42641 -10.07359,-22.5 -22.5,-22.5z"></path></g></g></svg>
            </a>
            <a href="https://www.youtube.com/channel/UCIxBHAl-5CvXseFnalrarnw" target="_blank" class="foo__socials-item" id="foo__socials-yt">
                    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="50" height="50" viewBox="0 0 225 225" style=" fill:#000000;"><g transform=""><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,225.98438v-225.98437h225.98438v225.98438z" fill="none"></path><path d="M112.99219,214.24219c-55.91883,0 -101.25,-45.33117 -101.25,-101.25v0c0,-55.91883 45.33117,-101.25 101.25,-101.25v0c55.91883,0 101.25,45.33117 101.25,101.25v0c0,55.91883 -45.33117,101.25 -101.25,101.25z" fill="#e80303"></path><g id="original-icon" fill="#ffffff"><path d="M177.3769,77.97843c-1.30997,-7.23052 -7.55159,-12.49609 -14.79496,-14.13997c-10.83936,-2.29887 -30.89989,-3.94275 -52.6043,-3.94275c-21.69157,0 -42.07316,1.64388 -52.92537,3.94275c-7.23052,1.64388 -13.48499,6.57554 -14.79496,14.13997c-1.32281,8.21942 -2.63278,19.72661 -2.63278,34.52157c0,14.79496 1.30997,26.30215 2.95386,34.52157c1.32281,7.23052 7.56444,12.49609 14.79496,14.13997c11.50719,2.29887 31.2338,3.94275 52.93821,3.94275c21.70441,0 41.43102,-1.64388 52.93821,-3.94275c7.23052,-1.64388 13.47214,-6.57554 14.79496,-14.13997c1.30997,-8.21942 2.95385,-20.06052 3.28777,-34.52157c-0.66783,-14.79496 -2.31171,-26.30215 -3.9556,-34.52157zM92.22883,135.51438v-46.02876l40.10821,23.01438z"></path></g></g></g></svg>
            </a>
    </div>
    <div class="foo__terms">
            <a href="#">Políticas de Privacidad</a>
            <a href="#">Términos y Condiciones</a>
            <a href="#">Políticas de Seguridad</a>
    </div>
    <div class="foo__support">
            <h3>Soporte Técnico</h3>
            <picture>
                    <source srcset="/static/img/white-icon_support.avif" type="image/avif">
                    <source srcset="/static/img/white-icon_support.webp" type="image/webp">
                    <img loading="lazy" src="/static/img/min/white-icon_support.png" type="image/png" alt="Support IMG">
            </picture>
            <a href="#">
                    <span>info@site.com</span>
                    <i class="fas fa-wrench"></i>
            </a>
    </div>
</footer>

app/templates/navbar.html
<header class="header">
    <div class="navbar-filter">
        <img src="/static/img/Ciervos.png" alt="Ciervos">
        <img src="/static/img/logo_ipn-white.png" alt="Ciervos">
        <img src="/static/img/CECyT%2012.png" alt="CECyT12">
        <div class="slogan">
            <div id="start">
                "La Técnica al Servicio de la Patria".
            </div>
            <div id="end">
                Instituto <br>
                Politécnico <br>
                Nacional.
            </div>
        </div>
    </div>
    <nav class="header__nav">
        <div class="dropmenu-box">
            <button type="button" id="dropmenu" readonly="menu">
                <span><i class="fas fa-bars"></i>&nbsp;&nbsp; Menu</span>
            </button>
        </div>
        <ul class="dropmenu-disable" id="nav_menu">
            <li><a href="/">Inicio</a></li>
            <li><a href="/presentation">Presentación</a></li>
            <li><a href="/vocational_test">Test</a></li>
            <li><a href="/careers">Carreras</a></li>
            <li><a href="/contact_us">Contacto</a></li>
        </ul>
    </nav>
</header>

app/templates/routes/career_administracion.html
{% extends 'base.html' %}

{% block title %} Administración {% endblock %}

{% block content %}
<div class="content_career">
    <div class="career_info">
        <div class="career-concept">
            <h3>¿Qué es?</h3>
            <p>
                La administración de empresas, administración de negocios, gestión empresarial o gestión de empresas es un estudio complejo y
                extenso que buscan mejorar la relación entre productividad, calidad, costos, administración, distribución y logística así como
                tiempo de producción, relación de trabajadores operarios y de confianza para mejorar de manera continua y eficiente la
                competitividad de una empresa o de un negocio. Su finalidad es lograr metas determinadas en plazos de tiempo óptimo constante
                para aumentar la productividad y la competitividad.
                Otro elemento comparativo es el paso del tiempo y su efecto en toda la organización. En un automóvil, las partes mecánicas se
                desgastarán con el tiempo, pero al estar normalizadas podrán sustituirse por otras, según un programa de mantenimiento que
                permitirá que el vehículo siga funcionando. En el caso de las personas, con el tiempo irán cambiando: la percepción, la
                experiencia, la motivación. El proceso de envejecimiento afectará a su actitud y su comportamiento. Además, los
                grupos de personas dentro de la organización actúan de forma distinta según el momento de la vida en el que se encuentren.
            </p>
        </div>
        <div class="career-program">
            <h3>Programa</h3>
            <table>
                <thead>
                    <tr>
                        <th>1°</th>
                        <th>2°</th>
                        <th>3°</th>
                        <th>4°</th>
                        <th>5°</th>
                        <th>6°</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Álgebra</th>
                        <th>Geometría y Trigonometría</th>
                        <th>Geometría Analítica</th>
                        <th>Cálculo Diferencial</th>
                        <th>Cáclulo Integral</th>
                        <th>Probabilidad y Estadística</th>
                    </tr>
                    <tr>
                        <th>Filosofía I</th>
                        <th>Filosofía II</th>
                        <th>Física I</th>
                        <th>Física II</th>
                        <th>Microeconomía</th>
                        <th>Macroeconomía</th>
                    </tr>
                    <tr>
                        <th>Computación Básica I</th>
                        <th>Computación Básica II</th>
                        <th>Química I</th>
                        <th>Química II</th>
                        <th>Inglés V</th>
                        <th>Inglés VI</th>
                    </tr>
                    <tr>
                        <th>Inglés I</th>
                        <th>Inglés II</th>
                        <th>Inglés III</th>
                        <th>Inglés IV</th>
                        <th>Derecho Mercantil</th>
                        <th>Orientación Juvenil y Profesional IV</th>
                    </tr>
                    <tr>
                        <th>Expresión Oral y Escrita I</th>
                        <th>Expresión Oral y Escrita II</th>
                        <th>Comunicación Científica</th>
                        <th>Derecho</th>
                        <th>Contabilidad III</th>
                        <th>Paquetería Administrativa</th>
                    </tr>
                    <tr>
                        <th>Desarrollo de Habilidades del Pensamiento</th>
                        <th>Biología Básica</th>
                        <th>Contabilidad I</th>
                        <th>Contabilidad II</th>
                        <th>Orientación Juvenil y Profesional III</th>
                        <th>Sistemas de Calidad</th>
                    </tr>
                    <tr>
                        <th>Historia de México Contemporáneo I</th>
                        <th>Historia de México Contemporáneo II</th>
                        <th>Entorno Socioeconómico de México</th>
                        <th>Cálculos Financieros II</th>
                        <th>Administraciónde Sueldos y Salarios</th>
                        <th>Nociones de Finanzas</th>
                    </tr>
                    <tr>
                        <th>Desarrollo Personal</th>
                        <th>Orientación Juvenil y Profesional II</th>
                        <th>Cáculos Financieros I</th>
                        <th>Administraciónde Capital Humano</th>
                        <th>Sistemas y Métodos Organizacionales</th>
                        <th>Producción</th>
                    </tr>
                    <tr>
                        <th>Orientación Juvenil y Profesional I</th>
                        <th>Optativa 1</th>
                        <th>Administración</th>
                        <th>Optativa 3</th>
                        <th>Mercadotecnia</th>
                        <th>Derecho Laboral</th>
                    </tr>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Optativa 2</th>
                        <th></th>
                        <th>Optativa 4</th>
                        <th>Optativa 5</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/routes/career_contabilidad.html
{% extends 'base.html' %}

{% block title %} Contabilidad {% endblock %}

{% block content %}
<div class="content_career">
    <div class="career_info">
        <div class="career-concept">
            <h3>¿Qué es?</h3>
            <p>
                La contabilidad es una disciplina que se encarga de estudiar, medir y analizar el patrimonio, la situación patrimonial
                económica y financiera de una empresa u organización, con el fin de facilitar la toma de decisiones en el seno de la misma
                y el control externo, presentando la información, previamente registrada, de manera sistemática y útil para las distintas partes
                interesadas.
                La contabilidad es una disciplina técnica que a partir del procesamiento de datos sobre la composición y evolución del
                patrimonio de un ente, los bienes de propiedad de terceros en su poder y ciertas contingencias produce información para
                la toma de decisiones de administradores y terceros interesados y para la vigilancia sobre los recursos y obligaciones del ente.
            </p>
        </div>
        <div class="career-program">
            <h3>Programa</h3>
            <table>
                <thead>
                    <tr>
                        <th>1°</th>
                        <th>2°</th>
                        <th>3°</th>
                        <th>4°</th>
                        <th>5°</th>
                        <th>6°</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Álgebra</th>
                        <th>Geometría y Trigonometría</th>
                        <th>Geometría Analítica</th>
                        <th>Cálculo Diferencial</th>
                        <th>Cáclulo Integral</th>
                        <th>Probabilidad y Estadística</th>
                    </tr>
                    <tr>
                        <th>Filosofía I</th>
                        <th>Filosofía II</th>
                        <th>Física I</th>
                        <th>Física II</th>
                        <th>Microeconomía</th>
                        <th>Macroeconomía</th>
                    </tr>
                    <tr>
                        <th>Computación Básica I</th>
                        <th>Computación Básica II</th>
                        <th>Química I</th>
                        <th>Química II</th>
                        <th>Inglés V</th>
                        <th>Inglés VI</th>
                    </tr>
                    <tr>
                        <th>Inglés I</th>
                        <th>Inglés II</th>
                        <th>Inglés III</th>
                        <th>Inglés IV</th>
                        <th>Derecho Mercantil</th>
                        <th>Orientación Juvenil y Profesional IV</th>
                    </tr>
                    <tr>
                        <th>Expresión Oral y Escrita I</th>
                        <th>Expresión Oral y Escrita II</th>
                        <th>Comunicación Científica</th>
                        <th>Derecho</th>
                        <th>Contabilidad III</th>
                        <th>Seguridad Social</th>
                    </tr>
                    <tr>
                        <th>Desarrollo de Habilidades del Pensamiento</th>
                        <th>Biología Básica</th>
                        <th>Contabilidad I</th>
                        <th>Contabilidad II</th>
                        <th>Orientación Juvenil y Profesional III</th>
                        <th>Nóminas</th>
                    </tr>
                    <tr>
                        <th>Historia de México Contemporáneo I</th>
                        <th>Historia de México Contemporáneo II</th>
                        <th>Entorno Socioeconómico de México</th>
                        <th>Cálculos Financieros II</th>
                        <th>Legislación Fiscal Personas Morales</th>
                        <th>Contabilidad de Costos</th>
                    </tr>
                    <tr>
                        <th>Desarrollo Personal</th>
                        <th>Orientación Juvenil y Profesional II</th>
                        <th>Cáculos Financieros I</th>
                        <th>Legislación Fiscal Personas Físicas</th>
                        <th>Derecho Laboral</th>
                        <th>Nociones de Auditoría</th>
                    </tr>
                    <tr>
                        <th>Orientación Juvenil y Profesional I</th>
                        <th>Legislación Fiscal</th>
                        <th>Paquetería Contable</th>
                        <th>Nociones de Finanzas y Presupuestos</th>
                        <th>Optativa 4</th>
                    </tr>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Optativa 2</th>
                        <th></th>
                        <th>Optativa 3</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/routes/contact.html
{% extends 'base.html' %}

{% block title %} Contacto {% endblock %}

{% block content %}
<div class="content_contact">
    <form action="{{ url_for('views.index') }}" method="POST" class="contact-form">
        <h3>Contáctanos</h3>
        <p>
            En caso de tener problemas con la plataforma, por favor háganos saber para poder
            reparar el error de forma inmediata.
        </p>
        <div class="form-group">
            <label for="name" id="label-name">Nombre</label>
            <input type="text" name="name" id="input-name" placeholder="Escribe tu Nombre...">
        </div>
        <div class="form-group">
            <label for="mail" id="label-mail">Correo</label>
            <input type="text" name="mail" id="input-mail" placeholder="Escribe tu Correo...">
        </div>
        <div class="form-group">
            <label for="boleta" id="label-boleta">Boleta</label>
            <input type="text" name="boleta" id="input-boleta" placeholder="Escribe tu Número de Boleta...">
        </div>
        <div class="form-group">
            <label for="message" id="label-message">Mensaje</label>
            <textarea type="text" name="message" id="input-message" placeholder="Escríbenos tu Mensaje..."></textarea>
        </div>
        <button type="submit" id="submit">
            <span>Enviar</span>
            <i class="fas fa-arrow-right"></i>
        </button>
    </form>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/routes/test.html
{% extends 'base.html' %}

{% block title %} Test {% endblock %}

{% block content %}
<div class="content-work_test">
    <div class="work_test">
        <form class="test-form" method="get">
            <h3 id="question_number"></h3>
            <p id="question_text"></p>
            <div id="group__answers">
                <span id="answerA" class="answers"></span>
                <span id="answerB" class="answers"></span>
                <span id="answerC" class="answers"></span>
                <span id="answerD" class="answers"></span>
                <span id="answerE" class="answers"></span>
            </div>
            <button type="submit" class="btn" id="next_question"><span id="next_question-txt">Siguiente</span><svg><rect x="0" y="0" fill="none"></rect></svg></button>
        </form>
        <div id="extra">
            <span id="note"></span>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static',filename='js/test.js') }}"></script>
{% endblock %}